# -*- coding: utf-8 -*-
"""
/***************************************************************************

                       EING GML import/export plugin

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-09
        copyright            : (C) 2022 by Noispot Innovations
 ***************************************************************************/
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Import class from file Import.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .import_export_plugin import GmlImportExport
    return GmlImportExport(iface)
